apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.instance.prefix }}-{{ .Release.Name }}-controller
spec:
  selector:
    matchLabels:
      app: {{ .Values.instance.prefix }}-{{ .Release.Name }}-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.instance.prefix }}-{{ .Release.Name }}-controller
    spec:
      terminationGracePeriodSeconds: 180

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:

      - name: controller
        image: hub.cerit.io/scipion/scipion-controller:latest
        imagePullPolicy: Always

        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

        ports:
        - containerPort: 8000
        env:
        - name: NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: INSTANCE_NAME
          value: {{ .Release.Name | quote }}
        - name: INSTANCE_PREFIX
          value: {{ .Values.instance.prefix | quote }}
        - name: OD_DATASET_SPACEIDSHORT
          value: {{ .Values.od.dataset.spaceIdShort | quote }}
        - name: OD_PROJECT_SPACEIDSHORT
          value: {{ .Values.od.project.spaceIdShort | quote }}
        volumeMounts:
        - name: shared
          mountPath: "/mnt/shared"
        - name: od-dataset-ro
          mountPath: "/mnt/od-dataset"
        - name: od-project-rw
          mountPath: "/mnt/od-project"
        - name: vol-dataset-rw
          mountPath: "/mnt/vol-dataset"
        - name: vol-project-rw
          mountPath: "/mnt/vol-project"
        resources:
          limits:
            cpu: 2
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi

      serviceAccountName: {{ .Values.instance.prefix }}-{{ .Release.Name }}-tool-spawner-sa
      volumes:

      # Onedata
      # ---------------------

      # Controller cloner
      - name: od-dataset-ro
        persistentVolumeClaim:
          claimName: pvc-{{ .Values.instance.prefix }}-{{ .Release.Name }}-od-dataset-{{ .Release.Namespace }}
          readOnly: true

      # Controller restore,autosave,finalsave
      - name: od-project-rw
        persistentVolumeClaim:
          claimName: pvc-{{ .Values.instance.prefix }}-{{ .Release.Name }}-od-project-{{ .Release.Namespace }}

      # Auto vol provisioning
      # ---------------------

      # Shared volume between Master and Controller
      - name: shared
        persistentVolumeClaim:
          claimName: pvc-{{ .Values.instance.prefix }}-{{ .Release.Name }}-shared-{{ .Release.Namespace }}

      # Master + Controller cloner (master - tmp)
      - name: vol-dataset-rw
        persistentVolumeClaim:
          claimName: pvc-{{ .Values.instance.prefix }}-{{ .Release.Name }}-vol-dataset-{{ .Release.Namespace }}-{{ .Values.od.dataset.spaceIdShort }}

# TODO RO for RW PVC does not work
#      # Master
#      - name: vol-dataset-ro
#        persistentVolumeClaim:
#          claimName: pvc-scipion-vol-dataset-$SUBST_NAMESPACE
#          readOnly: true

      # Master + Controller restore,autosave,finalsave
      - name: vol-project-rw
        persistentVolumeClaim:
          claimName: pvc-{{ .Values.instance.prefix }}-{{ .Release.Name }}-vol-project-{{ .Release.Namespace }}-{{ .Values.od.project.spaceIdShort }}
