apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.instance.prefix }}-{{ .Release.Name }}-vnc
spec:
  selector:
    matchLabels:
      app: {{ .Values.instance.prefix }}-{{ .Release.Name }}-vnc
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.instance.prefix }}-{{ .Release.Name }}-vnc
    spec:
      terminationGracePeriodSeconds: 180

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:

      - name: vnc
        image: hub.cerit.io/scipion/scipion-vnc:latest
        imagePullPolicy: Always

        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

        ports:
        - containerPort: 5901
        - containerPort: 6001
        env:
        - name: NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: INSTANCE_NAME
          value: {{ .Release.Name | quote }}
        - name: INSTANCE_PREFIX
          value: {{ .Values.instance.prefix | quote }}
        - name: OD_DATASET_SPACEIDSHORT
          value: {{ .Values.od.dataset.spaceIdShort | quote }}
        - name: OD_PROJECT_SPACEIDSHORT
          value: {{ .Values.od.project.spaceIdShort | quote }}
        - name: VNC_PASS
          value: {{ .Values.vnc.vncPassword | quote }}
        - name: USE_DISPLAY
          value: "1"
# USE_DISPLAY 1 is hardcoded in other files!
        - name: USE_VNCCLIENT
          value: {{ .Values.vnc.useVncClient | quote }}
        volumeMounts:
        - name: shared
          mountPath: "/mnt/shared"
{{ if .Values.vnc.useVncClient }}
        - name: cert-loadbalancer-vncclient
          mountPath: "/mnt/cert-loadbalancer-vncclient"
          readOnly: true
{{ end }}
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi

      volumes:

{{ if .Values.vnc.useVncClient }}
      # Certificate for VNC server
      - name: cert-loadbalancer-vncclient
        secret:
          secretName: {{ .Values.instance.prefix }}-{{ .Release.Name }}-{{ .Release.Namespace }}-dyn-cloud-e-infra-cz-tls
{{ end }}

      # Shared volume between vnc and Controller
      - name: shared
        persistentVolumeClaim:
          claimName: pvc-{{ .Values.instance.prefix }}-{{ .Release.Name }}-shared-{{ .Release.Namespace }}
