{{ if .Values.instance.microk8s }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-scipion-od-dataset-{{ .Release.Name }}-{{ .Release.Namespace }}
spec:
  accessModes:
    - ReadOnlyMany # RO
  capacity:
    storage: 5000Gi
  storageClassName: "onedata"
  csi:
    driver: csi-onedata
    nodePublishSecretRef:
      name: scipion-od-dataset-{{ .Release.Name }}-{{ .Release.Namespace }}
      namespace: {{ .Release.Namespace }}
    volumeHandle: pv-scipion-od-dataset-{{ .Release.Name }}-{{ .Release.Namespace }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-scipion-od-project-{{ .Release.Name }}-{{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany # RW
  capacity:
    storage: 5000Gi
  storageClassName: "onedata"
  csi:
    driver: csi-onedata
    nodePublishSecretRef:
      name: scipion-od-project-{{ .Release.Name }}-{{ .Release.Namespace }}
      namespace: {{ .Release.Namespace }}
    volumeHandle: pv-scipion-od-project-{{ .Release.Name }}-{{ .Release.Namespace }}
{{ end }}
