
# Required by pv-scipion-od (Onedata)

{{ if .Values.instance.microk8s }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Values.instance.prefix }}-{{ .Release.Name }}-od-dataset-{{ .Release.Namespace }}
spec:
  accessModes:
    - ReadOnlyMany # RO
  resources:
    requests:
      storage: 5000Gi
  storageClassName: "onedata"
  volumeName: pv-{{ .Values.instance.prefix }}-{{ .Release.Name }}-od-dataset-{{ .Release.Namespace }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Values.instance.prefix }}-{{ .Release.Name }}-od-project-{{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany # RW
  resources:
    requests:
      storage: 5000Gi
  storageClassName: "onedata"
  volumeName: pv-{{ .Values.instance.prefix }}-{{ .Release.Name }}-od-project-{{ .Release.Namespace }}
{{ end }}
