
# Dynamic volume provisioning

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Values.instance.prefix }}-{{ .Release.Name }}-shared-{{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Values.instance.prefix }}-{{ .Release.Name }}-vol-dataset-{{ .Release.Namespace }}-{{ .Values.od.dataset.spaceIdShort }}
{{ if .Values.instance.keepVolumes }}
  annotations:
    "helm.sh/resource-policy": keep
{{ end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5000Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Values.instance.prefix }}-{{ .Release.Name }}-vol-project-{{ .Release.Namespace }}-{{ .Values.od.project.spaceIdShort }}
{{ if .Values.instance.keepVolumes }}
  annotations:
    "helm.sh/resource-policy": keep
{{ end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5000Gi
  storageClassName: nfs-csi
