apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tool-spawner-rb-{{ .Release.Name }}
  annotations:
    "helm.sh/resource-policy": keep
roleRef:
  kind: Role
  name: tool-spawner-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: tool-spawner-sa-{{ .Release.Name }}
