apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tool-spawner-{{ .Release.Name }}
  annotations:
    "helm.sh/resource-policy": keep
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete", "describe"]

- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]

- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "delete"]

- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]

- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]
