apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.instance.prefix }}-{{ .Release.Name }}-od-dataset-{{ .Release.Namespace }}
#  annotations:
#    "helm.sh/resource-policy": keep
  labels:
    cerit-onedata-secret: "yes"
data:
  host: {{ .Values.od.dataset.host | b64enc | quote }} # host in base64 form
  onedata_token: {{ .Values.od.dataset.token | b64enc | quote }} # token in base64 form
  space_id: {{ .Values.od.dataset.spaceId | b64enc | quote }} # space-id in base64 form
  oneclient_options: LS1mb3JjZS1kaXJlY3QtaW8K # --force-direct-io
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.instance.prefix }}-{{ .Release.Name }}-od-project-{{ .Release.Namespace }}
#  annotations:
#    "helm.sh/resource-policy": keep
  labels:
    cerit-onedata-secret: "yes"
data:
  host: {{ .Values.od.project.host | b64enc | quote }} # host in base64 form
  onedata_token: {{ .Values.od.project.token | b64enc | quote }} # token in base64 form
  space_id: {{ .Values.od.project.spaceId | b64enc | quote }} # space-id in base64 form
  oneclient_options: LS1mb3JjZS1kaXJlY3QtaW8K # --force-direct-io
type: Opaque
