apiVersion: v1
kind: Service
metadata:
  name: scipion-vnc-svc-novnc-{{ .Release.Name }}
spec:
  selector:
    app: scipion-vnc-{{ .Release.Name }}
{{ if not .Values.instance.microk8s }}
  type: ClusterIP
  ports:
  - name: scipion-vnc-port-{{ .Release.Name }}
    port: 5901
    targetPort: 5901
{{ else }}
  type: NodePort
  ports:
  - name: http
    port: 5901
    targetPort: 5901
    nodePort: 32142
    protocol: TCP
{{ end }}
