apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.instance.prefix }}-{{ .Release.Name }}-rest
spec:
  selector:
    app: {{ .Values.instance.prefix }}-{{ .Release.Name }}-controller
  type: ClusterIP
  ports:
  - name: {{ .Values.instance.prefix }}-{{ .Release.Name }}-rest
    port: 8000
    targetPort: 8000
