apiVersion: batch/v1
kind: Job
#apiVersion: apps/v1
#kind: Deployment
metadata:
  name: {{ .Values.instance.prefix }}-{{ .Values.instance.name }}-tool-{{ .Values.job.name }}-{{ .Values.instance.submitpid }}
spec:
  ttlSecondsAfterFinished: 30
  backoffLimit: 0
  template:
    metadata:
      labels:
        name: {{ .Values.instance.prefix }}-{{ .Values.instance.name }}-tool-{{ .Values.job.name }}-{{ .Values.instance.submitpid }}
    spec:

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: {{ .Values.instance.prefix }}-{{ .Values.instance.name }}-tool-{{ .Values.job.name }}-{{ .Values.instance.submitpid }}
        image: hub.cerit.io/scipion/scipion-tool2:{{ .Values.job.tool }}-{{ .Values.instance.releaseChannel }}
        imagePullPolicy: Always

        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

        env:
        - name: INSTANCE_NAME
          value: {{ .Values.instance.name | quote }}
        - name: INSTANCE_PREFIX
          value: {{ .Values.instance.prefix | quote }}
        - name: ROOT_PASS
          value: "abc"
        - name: USER_PASS
          value: "abc"
        - name: TOOL_COMMAND
          value: {{ .Values.job.command | quote }}
        - name: SUBMIT_PID
          value: "-1"
        - name: XMIPP_IN_QUEUE
          value: {{ .Values.job.xmippInQueue | quote }}
        - name: JOB_NAME
          value: "{{ .Values.instance.name }}-{{ .Values.job.name }}-{{ .Values.instance.submitpid }}"
        - name: JOB_WORKDIR
          value: {{ .Values.job.workdir | quote }}
        volumeMounts:
        - name: shared
          mountPath: "/mnt/shared"
        - name: scipion-vol-dataset-rw
          mountPath: "/mnt/vol-dataset"
        - name: scipion-vol-project-rw
          mountPath: "/mnt/vol-project"
        resources:
          limits: # request is the same as limits if not specified
            cpu: {{ .Values.instance.maxcpu | quote }}
            memory: {{ .Values.instance.maxram | quote }}

      restartPolicy: Never
      volumes:

      - name: shared
        persistentVolumeClaim:
          claimName: pvc-{{ .Values.instance.prefix }}-{{ .Values.instance.name }}-shared-{{ .Release.Namespace }}

      - name: scipion-vol-dataset-rw
        persistentVolumeClaim:
          claimName: pvc-{{ .Values.instance.prefix }}-{{ .Values.instance.name }}-vol-dataset-{{ .Release.Namespace }}-{{ .Values.od.dataset.spaceIdShort }}

      - name: scipion-vol-project-rw
        persistentVolumeClaim:
          claimName: pvc-{{ .Values.instance.prefix }}-{{ .Values.instance.name }}-vol-project-{{ .Release.Namespace }}-{{ .Values.od.project.spaceIdShort }}
