
# Required by pv-scipion-od (Onedata)

{{ if .Values.instance.microk8s }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scipion-od-source-{{ .Release.Namespace }}
spec:
  accessModes:
    - ReadOnlyMany # RO
  resources:
    requests:
      storage: 5000Gi
  storageClassName: "onedata"
  volumeName: pv-scipion-od-source-{{ .Release.Namespace }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scipion-od-project-{{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany # RW
  resources:
    requests:
      storage: 5000Gi
  storageClassName: "onedata"
  volumeName: pv-scipion-od-project-{{ .Release.Namespace }}
{{ end }}
