apiVersion: v1
kind: Secret
metadata:
  name: scipion-od-source-{{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    cerit-onedata-secret: "yes"
data:
  host: {{ .Values.od.host | b64enc | quote }} # host in base64 form
  onedata_token: {{ .Values.od.source.token | b64enc | quote }} # token in base64 form
  space_id: {{ .Values.od.source.spaceId | b64enc | quote }} # space-id in base64 form
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: scipion-od-project-{{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    cerit-onedata-secret: "yes"
data:
  host: {{ .Values.od.host | b64enc | quote }} # host in base64 form
  onedata_token: {{ .Values.od.project.token | b64enc | quote }} # token in base64 form
  space_id: {{ .Values.od.project.spaceId | b64enc | quote }} # space-id in base64 form
type: Opaque
