apiVersion: v2
name: scipion-firefox
version: 0.1.0
appVersion: "100.0.0"
description: A Helm chart to deploy Firefox for Scipion in Kubernetes
icon: file://logo.png
keywords:
- scipion
- firefox
type: application
