
# Dynamic volume provisioning

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scipion-shared-{{ .Release.Name }}-{{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scipion-vol-dataset-{{ .Release.Name }}-{{ .Release.Namespace }}-{{ .Values.od.dataset.spaceId }}
{{ if .Values.instance.keepVolumes }}
  annotations:
    "helm.sh/resource-policy": keep
{{ end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5000Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scipion-vol-project-{{ .Release.Name }}-{{ .Release.Namespace }}-{{ .Values.od.project.spaceId }}
{{ if .Values.instance.keepVolumes }}
  annotations:
    "helm.sh/resource-policy": keep
{{ end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5000Gi
  storageClassName: nfs-csi
