apiVersion: batch/v1
kind: Job
metadata:
  name: scipion-firefox-{{ .Values.instance.name }}
spec:
  ttlSecondsAfterFinished: 0
  backoffLimit: 0
  template:
    metadata:
      labels:
        name: scipion-firefox-{{ .Values.instance.name }}
    spec:
      containers:
      - name: scipion-firefox-{{ .Values.instance.name }}
        image: hub.cerit.io/scipion/scipion-firefox:{{ .Values.instance.release_channel }}
        imagePullPolicy: Always
        env:
        - name: INSTANCE_NAME
          value: {{ .Values.instance.name | quote }}
        - name: FIREFOX_ARGS
          value: {{ .Values.firefox.args | quote }}
        volumeMounts:
        - name: shared
          mountPath: "/mnt/shared"
        - name: scipion-vol-dataset-rw
          mountPath: "/mnt/vol-dataset"
        - name: scipion-vol-project-rw
          mountPath: "/mnt/vol-project"
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
      restartPolicy: Never
      volumes:

      - name: shared
        persistentVolumeClaim:
          claimName: pvc-scipion-shared-{{ .Values.instance.name }}-{{ .Values.instance.namespace }}

      - name: scipion-vol-dataset-rw
        persistentVolumeClaim:
          claimName: pvc-scipion-vol-dataset-{{ .Values.instance.name }}-{{ .Values.instance.namespace }}-{{ .Values.od.sid.dataset }}

      - name: scipion-vol-project-rw
        persistentVolumeClaim:
          claimName: pvc-scipion-vol-project-{{ .Values.instance.name }}-{{ .Values.instance.namespace }}-{{ .Values.od.sid.project }}
