apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.instance.prefix }}-{{ .Release.Name }}-tool-spawner-rb
  annotations:
    "helm.sh/resource-policy": keep
roleRef:
  kind: Role
  name: {{ .Values.instance.prefix }}-{{ .Release.Name }}-tool-spawner
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.instance.prefix }}-{{ .Release.Name }}-tool-spawner-sa
