apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.instance.prefix }}-{{ .Release.Name }}-vnc
spec:
  selector:
    app: {{ .Values.instance.prefix }}-{{ .Release.Name }}-vnc
{{ if not .Values.instance.microk8s }}
  type: ClusterIP
  ports:
  - name: {{ .Values.instance.prefix }}-{{ .Release.Name }}-vnc
    port: 5901
    targetPort: 5901
{{ else }}
  type: NodePort
  ports:
  - name: http
    port: 5901
    targetPort: 5901
    nodePort: 32142
    protocol: TCP
{{ end }}
