apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.instance.prefix }}-{{ .Release.Name }}-x11
spec:
  selector:
    app: {{ .Values.instance.prefix }}-{{ .Release.Name }}-vnc
  type: ClusterIP
  ports:
  - name: {{ .Values.instance.prefix }}-{{ .Release.Name }}-x11
    port: 6001
    targetPort: 6001
