apiVersion: v1
kind: Service
metadata:
  name: scipion-master-svc-novnc-{{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: scipion-master-port-{{ .Release.Name }}
    port: 5901
    targetPort: 5901
  selector:
    app: scipion-master-{{ .Release.Name }}
