apiVersion: v1
kind: Service
metadata:
  name: scipion-controller-svc-rest-{{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: scipion-controller-port-{{ .Release.Name }}
    port: 8000
    targetPort: 8000
  selector:
    app: scipion-controller-{{ .Release.Name }}
